### ISSUE TITLE
Sort $networks by ssid, only display each ssid once …

### ISSUE THREAD

**Issue by fooness** [sanchescom/php-wifi#10]
Is it possible to sort the $networks array(?) alphabetically by ssid and also to display each ssid only once?

Tried it with `array_unique()`, but couldn’t figure out how to modify $networks in any way.

Here’s what I’m using on my Kirby CMS page:

```php
<?php use Sanchescom\WiFi\WiFi; $networks = WiFi::scan()->getAll() ?>
<?php foreach ($networks as $network): ?>
            <option value="<?= strtolower($network); ?>"><?= $network->ssid ?></option>
<?php endforeach ?>
```

**Comment by sanchescom** [comment]
Yes, it is quietly easy. Method 'scan()' return a collection. Just do the next thing:

`
$networks = \Sanchescom\WiFi\WiFi::scan()->unique('ssid')->sortBy('ssid')->getAll();
`

**Comment by fooness** [comment]
Thank you so much, that works perfectly.

Is there any documentation available for questions like mine above? Feels like there’s very lots of great features in php-wifi.

**Comment by sanchescom** [comment]
Oh, I didn't even think of that. I will definitely expand the documentation. Thanks a lot.
