### ISSUE TITLE
We are getting this issue.

### ISSUE THREAD

**Issue by shantun001** [sanchescom/php-wifi#3]
Hello,

Please checked error screenshot.
![Screenshot_1](https://user-images.githubusercontent.com/45560508/58243284-feb9af80-7d6d-11e9-8b2b-102610071e51.png)

![Screenshot_2](https://user-images.githubusercontent.com/45560508/58243365-201a9b80-7d6e-11e9-862f-2dba560a20ed.png)

Fatal error: Uncaught Error: Class 'Sanchescom\WiFi\WiFi' not found in C:\xamppnew\htdocs\Net_Wifi-master\seond\tests\demo.php:8 Stack trace: #0 C:\xamppnew\htdocs\Net_Wifi-master\seond\tests\demo.php(20): Example->getAllNetworks() #1 {main} thrown in C:\xamppnew\htdocs\Net_Wifi-master\seond\tests\demo.php on line 8

![Screenshot_3](https://user-images.githubusercontent.com/45560508/58243443-46403b80-7d6e-11e9-8a08-3f8d92794714.png)

Please Help me to solve this issue.

Thank you.

**Comment by sanchescom** [comment]
Hi,
You need to add `require __DIR__ . '/../../vendor/autoload.php';` in the top of the file.
