### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by rijotech** [sanchescom/php-wifi#9]
How can I exactly install this on a debian OS?

**Comment by sanchescom** [comment]
You need to install nmcli utility for debian. If you have it then show me the error which you get.

**Comment by rijotech** [comment]
I have installed nmcli and composer, cloned your repo go to my root directory ~ but when I execute the command composer require pi/php-wifi this is what is get.

  [InvalidArgumentException]
  Could not find a matching version of package /home/pi/php-wifi. Check the package spelling, your version constraint and
  that the package is available in a stability which matches your minimum-stability (stable).


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by rijotech** [comment]
I managed to install everthing, nmcli composer and sanchescom php-wifi but when I create a php file with the Usage codes all I get is a error 500.
https://ibb.co/4MZ2tP4
https://ibb.co/b11CBzW

**Comment by sanchescom** [comment]
Probably you forgot to include vendor autoload file. Also you need to set correct credentials for wifi network. I fixed readme look at it and try again please.
